name: Weekly Release

# Build a fresh image every week.
on:
  schedule:
    - cron: "0 14 * * 1" # run at 9am eastern US time every Monday
  push:
    branches:
      - main

env:
  LATEST_GO_VERSION: "1.19"

jobs:
  build_and_upload_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.18"
          - "1.19"
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push Images Tagged with Go Version
        uses: docker/build-push-action@v3
        with:
          build-args: |
            GO_VERSION=${{ matrix.go-version }}
          platforms: linux/amd64 # GitHub only offers AMD64 codespaces
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.go-version }}
          cache-from: type=gha
          # mode=max means "cache everything possible". This ensures maximum
          # use of the cache, but will use up GitHub's 10 GB cache size limit
          # faster.
          cache-to: type=gha,mode=max
      - name: Push 'latest' tag
        if: ${{ matrix.go-version == env.LATEST_GO_VERSION }}
        run: |
          docker image tag ghcr.io/${{ github.repository }}:${{ env.LATEST_GO_VERSION }} ghcr.io/${{ github.repository }}:latest
          docker image push ghcr.io/${{ github.repository }}:latest
